name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: List target files
        run: ls -la target/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ShiftFplugin-JAR
          path: target/ShiftFplugin-*.jar  # 确保文件存在
